apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-app
  namespace: devsu-demo
spec:
  ingressClassName: nginx
  rules:
    - host: devsu.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsu-app
                port:
                  number: 80

