apiVersion: v1
kind: Service
metadata:
  name: devsu-app
  namespace: devsu-demo
spec:
  type: ClusterIP
  selector:
    app: devsu-app
  ports:
    - name: http
      port: 80
      targetPort: 8000

